FROM node:20-slim

WORKDIR /app/web-app

COPY web-app/package*.json /app/web-app/
RUN npm install --legacy-peer-deps

COPY web-app /app/web-app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
