FROM node:20-slim

WORKDIR /app/web-ui

COPY web-ui/package*.json /app/web-ui/
RUN npm install

COPY web-ui /app/web-ui

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
